project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - reference/index.qmd
    - reference/api/index.qmd
    - reference/api/*.qmd
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - README.md
    - tutorial.qmd

website:
  title: "ubc_mds_helper"
  navbar:
    left:
      - text: "Home"
        href: README.md
      - text: "Reference"
        href: reference/api/index.qmd
      - text: "Project"
        menu:
          - text: "Contributing"
            href: CONTRIBUTING.md
          - text: "Code of Conduct"
            href: CODE_OF_CONDUCT.md
          - text: "README"
            href: README.md
          - text: "Tutorial"
            href: tutorial.qmd

        
format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  package: ubc_mds_helper
  dir: reference/api
  sections:
    - title: UBC MDS Helper
      desc: Functions to help you survive in the MDS program.
      contents:
        - assessments.late_assignment
        - grade.needed_to_pass
        - progress.visualize_program_progress
        - status.status
