name: Build process for test suite
# Run the test suite on pull requests and pushes to the main branch
on:
  pull_request:
  push:
    branches:
      - main
      - build_action_workflow
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    env:
      MPLBACKEND: Agg # fixes bug to prevent Tkinter from being invoked and a test failing because of this
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4.5.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch and uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch uv

      - name: Install dependencies
        run: | 
          pip install -e ".[tests]"
          
      - name: Run test suite with coverage
        run: hatch run +py=${{ matrix.python-version }} test:run